#!/bin/bash

# This wrapper script runs the binary generated by calculatePI_build.sh.
# If an alternative binary is provided as a parameter, then runs that binary



# Path where executable file is.
# If no parameter, it is the build path generated by the cmake scripts
EXECPATH=${1:-$BUILDPATH/src/main}
echo "BUILD path is $BUILDPATH"

# TODO test if exec file exists
if [ ! -e $EXECPATH ]; then
   echo "Binary file $EXECPATH missing. Run calculatePI_build.sh wrapper first. Exiting..."
   exit 1
fi

# Execute generated binary if available
echo "Found executable in $EXECPATH"
echo "Starting computation..."
$EXECPATH

echo "Result can be found in $(basename EXECPATH)"

